"""The replay script: a deterministic Playwright program for one flow.

The Generator writes it; the replay runner executes it with no agent in the loop
(arch doc 6). Two parts of that contract are load-bearing and easy to get wrong:

- The runner regex-scrapes the script for `onboarding-[\\w-]+\\.metadata\\.json`
  and `onboarding-[\\w-]+\\.questions\\.json` and writes both documents into the
  temp workdir under exactly those names. A script that references its pair any
  other way materializes nothing and fails on read.
- Status is reported twice: `last-run.json` beside the script AND one
  `RRSTATUS <json>` line on stdout. The runner prefers the file and falls back
  to the line; omitting them makes it guess.

The script is assembled as a list of blocks so a block can be appended in the
same call that appends a question and a metadata field. One script per flow,
branching on its input: the number of paths is the product of the gate
cardinalities, so per-path scripts would leave any unenumerated combination with
no script at all.
"""

import json

# Refused before any click, in the script as well as in the agents. On the
# script's first run there is no agent watching, so the denylist has to travel
# with it. Binding and paying are irreversible and external.
_DENYLIST = [
    "pay", "bind", "purchase", "checkout", "place order", "confirm payment",
]

_HEADER = """// Replay script for {carrier} / {business_type} / {insurance_type}.
// Generated by Trailblazer. One script for the whole flow: it reads the client's
// answers and sets each gate to what they name, rather than one script per path.
//
// Invocation: node {script_name} <client-answers.json> [--config <creds.json>]
//
// Its documents are materialized by the runner under exactly these names:
//   onboarding-{slug}.metadata.json
//   onboarding-{slug}.questions.json
// The runner finds them by regex-scraping this file, so these string literals
// are the loading mechanism and cannot be built up from parts.

const fs = require('fs');
const path = require('path');
const {{ chromium }} = require('playwright');

const METADATA_FILE = 'onboarding-{slug}.metadata.json';
const QUESTIONS_FILE = 'onboarding-{slug}.questions.json';

const metadata = JSON.parse(fs.readFileSync(path.join(__dirname, METADATA_FILE), 'utf8'));
const questions = JSON.parse(fs.readFileSync(path.join(__dirname, QUESTIONS_FILE), 'utf8'));

// Never pay, never bind. Checked against the resolved element's accessible name
// before any click, because irreversible external actions cannot be undone by a
// later run.
const DENYLIST = {denylist};

function assertClickable(name) {{
  const lowered = (name || '').toLowerCase();
  for (const term of DENYLIST) {{
    if (lowered.includes(term)) {{
      throw new Error(`refusing to click ${{name}}: matches denylist term "${{term}}"`);
    }}
  }}
}}

async function clickSafely(page, selector) {{
  const el = page.locator(selector).first();
  assertClickable(await el.getAttribute('aria-label') || await el.innerText().catch(() => ''));
  await el.click();
}}

// A required answer the client did not give fails the stage. A `||` fallback
// here would invent a value and quote on a fact nobody supplied.
function requiredAnswer(answers, canonical, questionId) {{
  const value = answers[canonical];
  if (value === undefined || value === null || value === '') {{
    throw new Error(`missing required answer for ${{canonical}} (${{questionId}})`);
  }}
  return value;
}}

function optionalAnswer(answers, canonical) {{
  const value = answers[canonical];
  return value === undefined || value === null || value === '' ? null : value;
}}

function loadAnswers(file) {{
  const raw = JSON.parse(fs.readFileSync(file, 'utf8'));
  return raw.answers || raw;
}}

function loadConfig(file) {{
  if (!file) return {{}};
  const raw = JSON.parse(fs.readFileSync(file, 'utf8'));
  // Exactly these four keys. Reading any other name yields an empty password
  // that still gets typed, so the portal reports bad credentials, not a bug.
  return {{
    LOGIN_EMAIL: raw.LOGIN_EMAIL,
    LOGIN_PASSWORD: raw.LOGIN_PASSWORD,
    MFA_CARRIER_ID: raw.MFA_CARRIER_ID,
    HEADLESS: raw.HEADLESS,
  }};
}}

const status = {{
  outcome: 'stuck',
  reachedQuote: false,
  stoppedReason: null,
  premium: null,
  premiumDisplay: null,
  quoteNumber: null,
  quoteSaved: false,
  quoteUrl: null,
  bindUrl: null,
  bindControlLabel: null,
  documents: [],
}};

// Both are required: the runner prefers the file, falls back to the line, and
// falls back again to parsing log text.
function reportStatus() {{
  fs.writeFileSync(path.join(__dirname, 'last-run.json'), JSON.stringify(status, null, 2));
  process.stdout.write(`RRSTATUS ${{JSON.stringify(status)}}\\n`);
}}

async function main() {{
  const answersFile = process.argv[2];
  const configIndex = process.argv.indexOf('--config');
  const config = loadConfig(configIndex === -1 ? null : process.argv[configIndex + 1]);
  const answers = loadAnswers(answersFile);

  const launchOptions = {{ headless: config.HEADLESS !== false }};
  // Proxy-first: when RR_PROXY_SERVER is set, egress goes through it, never direct.
  if (process.env.RR_PROXY_SERVER) {{
    launchOptions.proxy = {{
      server: process.env.RR_PROXY_SERVER,
      password: process.env.RR_PROXY_PASSWORD,
    }};
  }}
  if (process.env.RR_BROWSER_CHANNEL) launchOptions.channel = process.env.RR_BROWSER_CHANNEL;

  const browser = await chromium.launch(launchOptions);
  const context = await browser.newContext(
    process.env.RR_USER_AGENT ? {{ userAgent: process.env.RR_USER_AGENT }} : {{}}
  );
  const page = await context.newPage();

  try {{
"""

_FOOTER = """
    reportStatus();
  } finally {
    await browser.close();
  }
}

main().catch((err) => {
  // An uncaught throw still has to report, or the runner cannot tell a crash
  // from a stall.
  status.reachedQuote = false;
  status.outcome = 'stuck';
  status.stoppedReason = err && err.message ? err.message : String(err);
  reportStatus();
  process.exitCode = 1;
}).then(() => {
  // Exit 0 for quote and appetite-decline: a decline is a successful run.
  if (process.exitCode === undefined || process.exitCode === 0) {
    process.exitCode = (status.reachedQuote || status.outcome === 'appetite-decline') ? 0 : 1;
  }
});
"""


def slug(carrier: str, business_type: str, insurance_type: str) -> str:
    """The flow's identity triple, as the `onboarding-<slug>` filename infix."""
    parts = [carrier, business_type, insurance_type]
    return "-".join(
        "".join(ch if ch.isalnum() else "-" for ch in p.lower()).strip("-") for p in parts
    )


def header(carrier: str, business_type: str, insurance_type: str, script_name: str) -> str:
    """The script's preamble: document loading, denylist, answer access, status."""
    return _HEADER.format(
        carrier=carrier,
        business_type=business_type,
        insurance_type=insurance_type,
        script_name=script_name,
        slug=slug(carrier, business_type, insurance_type),
        denylist=json.dumps(_DENYLIST),
    )


def stage_block(stage_name: str, url: str) -> str:
    """Open one stage: navigate to it and mark it in the log the runner parses."""
    lines = [f"    // --- stage: {stage_name} ---", f"    console.log('stage {stage_name}');"]
    if url:
        lines.append(f"    await page.goto({json.dumps(url)}, {{ waitUntil: 'domcontentloaded' }});")
    return "\n".join(lines) + "\n"


def _guard(conditional: tuple[str, str] | None) -> tuple[str, str, str]:
    """Open, indent and close for a block that runs only on one branch.

    `conditional` is the parent gate's questionId and the value that reveals
    this control. Without the guard the script sets a control that is not
    mounted on any other branch, and reads an answer the client was never asked
    for: every path but the one the crawl published fails.

    The parent's variable is in scope because blocks are emitted in the order
    the controls were appended, and a control is revealed only after the gate
    that revealed it was filled.
    """
    if conditional is None:
        return "", "", ""
    parent, value = conditional
    return (
        f"    if (String(v_{parent}) === {json.dumps(value)}) {{" + "\n",
        "    ",
        "    }" + "\n",
    )


def fill_block(
    question_id: str,
    canonical: str,
    selector: str,
    required: bool,
    intent: str,
    conditional: tuple[str, str] | None = None,
) -> str:
    """Set one control from the client's answer for `canonical`.

    The answer is read by canonical, not hardcoded: a hardcoded gate answer
    discards what the client actually said and quotes the wrong branch.
    """
    accessor = (
        f"requiredAnswer(answers, {json.dumps(canonical)}, {json.dumps(question_id)})"
        if required
        else f"optionalAnswer(answers, {json.dumps(canonical)})"
    )
    var = f"v_{question_id}"
    lines = [f"    const {var} = {accessor};"]
    guard = "" if required else f"    if ({var} !== null) "

    if intent == "select":
        body = f"await page.selectOption({json.dumps(selector)}, String({var}));"
    elif intent == "check":
        body = f"await page.setChecked({json.dumps(selector)}, Boolean({var}));"
    elif intent == "advance":
        body = f"await clickSafely(page, {json.dumps(selector)});"
    else:
        body = f"await page.fill({json.dumps(selector)}, String({var}));"

    lines.append(f"{guard}{'' if guard else '    '}{body}")
    open_, pad, close = _guard(conditional)
    return open_ + "".join(f"{pad}{line}\n" for line in lines) + close


def option_block(
    question_id: str,
    canonical: str,
    options: list[tuple[str, str]],
    required: bool,
    conditional: tuple[str, str] | None = None,
) -> str:
    """Set a control whose choices are separately clickable, e.g. a radio group.

    The chosen branch comes from the client's answer. Every option the crawl
    walked gets a branch; an answer matching none of them fails loudly rather
    than falling through to a default that was never tested.
    """
    accessor = (
        f"requiredAnswer(answers, {json.dumps(canonical)}, {json.dumps(question_id)})"
        if required
        else f"optionalAnswer(answers, {json.dumps(canonical)})"
    )
    var = f"v_{question_id}"
    lines = [f"    const {var} = {accessor};"]
    for i, (label, selector) in enumerate(options):
        kw = "if" if i == 0 else "else if"
        lines.append(f"    {kw} (String({var}) === {json.dumps(label)}) "
                     f"await clickSafely(page, {json.dumps(selector)});")
    if options:
        tail = (
            f"    else if ({var} !== null) throw new Error("
            f"`no walked option for ${{{var}}} on {question_id}`);"
        )
        lines.append(tail)
    open_, pad, close = _guard(conditional)
    return open_ + "".join(f"{pad}{line}\n" for line in lines) + close


def advance_block(selector: str) -> str:
    """Click the control that moves the flow to the next stage."""
    return f"    await clickSafely(page, {json.dumps(selector)});\n"


def footer() -> str:
    """Status reporting and the exit-code rule."""
    return _FOOTER
